import { PDFDocument, StandardFonts } from 'pdf-lib'
import { describe,expect,it } from 'vitest'
import { addPageNumbers, cleanMetadata, copySelectedPages, imagesToPdf, inspectPdf, mergePdfs, reorderPages, rotatePages, splitPdf } from './operations'

async function fixture(name:string,pages=3){const pdf=await PDFDocument.create();const font=await pdf.embedFont(StandardFonts.Helvetica);for(let index=0;index<pages;index+=1){const page=pdf.addPage(index%2?[792,612]:[612,792]);page.drawText(`Page ${index+1}`,{x:40,y:700-(index%2?120:0),font,size:18})}return new File([await pdf.save() as BlobPart],name,{type:'application/pdf'})}

describe('PDF operations',()=>{
  it('merges documents',async()=>{const output=await mergePdfs([await fixture('a.pdf',2),await fixture('b.pdf',3)]);expect((await PDFDocument.load(await output.arrayBuffer())).getPageCount()).toBe(5)})
  it('extracts and reorders pages',async()=>{const source=await fixture('source.pdf',3);const extracted=await copySelectedPages(source,[2,0]);expect((await PDFDocument.load(await extracted.arrayBuffer())).getPageCount()).toBe(2);const reordered=await reorderPages(source,[2,1,0]);expect((await PDFDocument.load(await reordered.arrayBuffer())).getPageCount()).toBe(3)})
  it('rotates selected pages',async()=>{const output=await rotatePages(await fixture('rotate.pdf',1),[0],90);expect((await PDFDocument.load(await output.arrayBuffer())).getPage(0).getRotation().angle).toBe(90)})
  it('adds page numbers',async()=>{const output=await addPageNumbers(await fixture('number.pdf',2),{selected:[0,1],start:4,size:12,position:'bottom-center',prefix:'p. '});expect((await PDFDocument.load(await output.arrayBuffer())).getPageCount()).toBe(2)})
  it('creates split ZIP output',async()=>{const output=await splitPdf(await fixture('split.pdf',3),[[0],[1,2]]);expect(output.type).toBe('application/zip');expect(output.size).toBeGreaterThan(100)})
  it('converts a JPG image to PDF',async()=>{const bytes=Buffer.from('/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAP//////////////////////////////////////////////////////////////////////////////////////2wBDAf//////////////////////////////////////////////////////////////////////////////////////wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIQAxAAAAF//8QAFBABAAAAAAAAAAAAAAAAAAAAAP/aAAgBAQABBQJ//8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAgBAwEBPwF//8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAgBAgEBPwF//8QAFBABAAAAAAAAAAAAAAAAAAAAAP/aAAgBAQAGPwJ//8QAFBABAAAAAAAAAAAAAAAAAAAAAP/aAAgBAQABPyF//9oADAMBAAIAAwAAABD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAEDAQE/EH//xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAECAQE/EH//xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEBAAE/EH//2Q==','base64');const output=await imagesToPdf([new File([bytes],'pixel.jpg',{type:'image/jpeg'})],{pageSize:'a4',margin:24,fit:'fit'});expect((await PDFDocument.load(await output.arrayBuffer())).getPageCount()).toBe(1)})
  it('reports page dimensions and metadata cleanup',async()=>{const source=await fixture('meta.pdf',2);const pdf=await PDFDocument.load(await source.arrayBuffer());pdf.setAuthor('PDFHope test');const named=new File([await pdf.save() as BlobPart],'meta.pdf',{type:'application/pdf'});const info=await inspectPdf(named);expect(info.pages.map((page)=>page.orientation)).toEqual(['Portrait','Landscape']);const cleaned=await cleanMetadata(named);expect(cleaned.report.removed).toContain('author')})
})
