import { ArrowRight, Clock3, LockKeyhole, Search, ShieldCheck, Smartphone, Sparkles, Zap } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { categories, getTool, tools } from '../data/tools'
import { ToolCard } from '../components/ToolCard'
import { useSeo } from '../hooks/useSeo'

const categoryCopy:Record<string,string>={Organize:'Combine, split, reorder and refine pages',Convert:'Move between PDFs and image formats',Optimize:'Make documents leaner and easier to share',Secure:'Remove metadata and protect privacy',Edit:'Add useful content to your document',Inspect:'Understand what is inside your PDF',Advanced:'Handle complex scanning and print workflows'}

export function HomePage(){useSeo('Every PDF tool you need','Fast, private PDF tools that process files locally in your browser.','/');const[query,setQuery]=useState(''),navigate=useNavigate(),recent=useMemo(()=>{try{return(JSON.parse(localStorage.getItem('pdfhope-recent')||'[]') as string[]).map(getTool).filter(Boolean).slice(0,4)}catch{return[]}},[]);const filtered=tools.filter((tool)=>`${tool.name} ${tool.short}`.toLowerCase().includes(query.toLowerCase())).slice(0,6);useEffect(()=>{const key=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();document.getElementById('home-search')?.focus()}};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[]);return <main>
  <section className="hero"><div className="eyebrow"><Sparkles size={15}/> PDF work, without the waiting room</div><h1>Every <span className="hero-emphasis">PDF tool</span><br/>you need.</h1><p>Fast, focused PDF utilities that run in your browser. Your documents stay under your control.</p><div className="hero-search-wrap"><label className="search-box"><Search aria-hidden="true"/><input id="home-search" type="search" value={query} onChange={(event)=>setQuery(event.target.value)} onKeyDown={(event)=>{if(event.key==='Enter'&&filtered[0])navigate(`/${filtered[0].slug}`)}} placeholder="What do you want to do with a PDF?" aria-label="Search PDF tools"/><kbd>Ctrl K</kbd></label>{query&&<div className="hero-results">{filtered.map((tool)=><Link to={`/${tool.slug}`} key={tool.slug}><strong>{tool.name}</strong><span>{tool.short}</span><ArrowRight size={16}/></Link>)}</div>}</div><div className="trust-row"><span><LockKeyhole size={16}/> Local processing</span><span>No signup</span><span>Works on mobile</span></div></section>
  <section className="tools-section"><div className="section-heading"><div><span className="kicker">Start here</span><h2>Popular tools</h2></div><Link to="/tools">Browse all tools <ArrowRight size={16}/></Link></div><div className="tool-grid">{tools.filter((tool)=>tool.popular).slice(0,10).map((tool)=><ToolCard key={tool.slug} tool={tool}/>)}</div></section>
  {recent.length>0&&<section className="recent-section"><div className="section-heading"><div><span className="kicker">Stored only in this browser</span><h2>Recently used</h2></div></div><div className="recent-row">{recent.map((tool)=><Link key={tool!.slug} to={`/${tool!.slug}`}><Clock3 size={18}/><span><strong>{tool!.name}</strong><small>{tool!.category}</small></span></Link>)}</div></section>}
  <section className="category-section"><span className="kicker">One focused toolkit</span><h2>Find the right tool</h2><div className="category-grid">{categories.map((category)=><Link to={`/tools?category=${category}`} key={category}><strong>{category}</strong><p>{categoryCopy[category]}</p><span>{tools.filter((tool)=>tool.category===category).length} tools <ArrowRight size={14}/></span></Link>)}</div></section>
  <section className="privacy-band"><div className="privacy-orbit"><ShieldCheck size={42}/></div><div><span className="kicker">Designed for privacy</span><h2>Your browser is the workspace.</h2><p>For supported tools, processing happens on your device. PDFHope does not need a file-upload server to merge, split, inspect, or edit your documents.</p></div><Link to="/privacy">How local processing works <ArrowRight size={16}/></Link></section>
  <section className="why-section"><div><span className="kicker">Why PDFHope</span><h2>Serious tools.<br/>Less friction.</h2><p>No account wall, noisy dashboard, or server queue between you and the result.</p></div><div className="benefit-grid"><article><Zap/><h3>Fast by design</h3><p>Route-level code splitting keeps the homepage light and loads PDF engines only when needed.</p></article><article><LockKeyhole/><h3>Local-first</h3><p>Files are processed with browser APIs for the tools currently available.</p></article><article><Smartphone/><h3>Made for any screen</h3><p>Large controls and responsive layouts make quick edits practical on mobile.</p></article><article><Search/><h3>Easy to find</h3><p>Clear names, search, favorites, and recent tools help you return to the right workflow.</p></article></div></section>
  <section className="seo-copy"><div><span className="kicker">Useful by default</span><h2>What makes a browser PDF tool different?</h2></div><p>Traditional online PDF tools often send documents to a remote server for processing. PDFHope’s current tools use JavaScript PDF libraries, browser canvas rendering, and local memory instead. That means there is no server upload step for supported operations. Browser memory still has limits, especially for image-heavy documents, so the interface warns about large files and reports failures clearly.</p></section>
  <section className="faq home-faq"><span className="kicker">Common questions</span><h2>PDFHope FAQ</h2><details><summary>Is PDFHope free?</summary><p>The local tools are free to use and do not require an account. Server-based document conversion is subject to service availability and usage limits.</p></details><details><summary>Does PDFHope upload my files?</summary><p>Most PDF tools process files locally in your browser. Word to PDF and PDF to Word clearly identify their secure server conversion step and send the selected file only when you choose Convert.</p></details><details><summary>Which browsers work best?</summary><p>Current versions of Chrome, Edge, Firefox, and Safari are recommended. Large files work best on devices with more available memory.</p></details></section>
  <div className="ad-slot" aria-label="Reserved advertising space"><span>Reserved for a future clearly labeled advertisement</span></div>
  </main>}
