import { ArrowDown, ArrowUp, Bold, Download, FilePlus, FileText, Highlighter, ImagePlus, Italic, Minus, MousePointer2, PenLine, Plus, Redo2, Square, Trash2, Type, Undo2, X } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import { openRenderedPdf } from '../lib/pdf/render'
import { downloadBlob } from '../lib/files'
import { useSeo } from '../hooks/useSeo'

type Obj={id:number;page?:number;kind:'text'|'shape'|'highlight'|'image'|'signature'|'drawing';x:number;y:number;w:number;h:number;color:string;text?:string;size?:number;bold?:boolean;italic?:boolean}
type Hist={objects:Obj[];deleted:number[];order:number[]}
const clone=(x:Hist):Hist=>JSON.parse(JSON.stringify(x))
export function PdfEditor(){
  useSeo('PDF Editor — Add text, signatures, and annotations','Edit PDFs locally in your browser with text overlays, images, signatures, drawings, page edits, and undo/redo.','/edit-pdf')
  const [file,setFile]=useState<File|null>(null),[doc,setDoc]=useState<any>(null),[page,setPage]=useState(1),[scale,setScale]=useState(1),[tool,setTool]=useState<'select'|'text'|'highlight'|'shape'|'draw'|'image'|'signature'>('select'),[objects,setObjects]=useState<Obj[]>([]),[deleted,setDeleted]=useState<number[]>([]),[order,setOrder]=useState<number[]>([]),[history,setHistory]=useState<Hist[]>([]),[future,setFuture]=useState<Hist[]>([]),[error,setError]=useState(''),[pages,setPages]=useState(0),[selected,setSelected]=useState<number|null>(null),[dark,setDark]=useState(false)
  const input=useRef<HTMLInputElement>(null),canvas=useRef<HTMLCanvasElement>(null),wrap=useRef<HTMLDivElement>(null),drawing=useRef(false),start=useRef({x:0,y:0})
  const snapshot=()=>({objects:clone({objects,deleted,order}).objects,deleted:[...deleted],order:[...order]})
  const commit=(next:Partial<Hist>)=>{setHistory(h=>[...h,snapshot()]);setFuture([]);if(next.objects)setObjects(next.objects);if(next.deleted)setDeleted(next.deleted);if(next.order)setOrder(next.order)}
  const load=async(next:File)=>{setFile(next);setError('');try{const pdf=await openRenderedPdf(next);setDoc(pdf);setPages(pdf.numPages);setOrder(Array.from({length:pdf.numPages},(_,i)=>i+1));setPage(1)}catch(e){setError(/password|encrypted/i.test(String(e))?'This PDF is password-protected. Unlock it with permission first.':'This PDF appears corrupted or unsupported.')}}
  useEffect(()=>{if(!doc||!canvas.current)return;const run=async()=>{const p=await doc.getPage(page),v=p.getViewport({scale});canvas.current!.width=Math.ceil(v.width);canvas.current!.height=Math.ceil(v.height);await p.render({canvasContext:canvas.current!.getContext('2d')!,viewport:v}).promise};void run().catch(()=>setError('This page could not be rendered.'))},[doc,page,scale])
  const add=(kind:Obj['kind'])=>{const id=Date.now();commit({objects:[...objects,{id,page,kind,x:80,y:100,w:170,h:42,color:kind==='highlight'?'#f2be44':'#143b36',text:kind==='text'?'New text':kind==='signature'?'Signature':kind==='image'?'Image':'',size:18}]});setSelected(id)}
  const remove=()=>{if(selected!==null)commit({objects:objects.filter(o=>o.id!==selected)});setSelected(null)}
  const undo=()=>{const prev=history.at(-1);if(!prev)return;setFuture(f=>[snapshot(),...f]);setHistory(h=>h.slice(0,-1));setObjects(prev.objects);setDeleted(prev.deleted);setOrder(prev.order)}
  const redo=()=>{const next=future[0];if(!next)return;setHistory(h=>[...h,snapshot()]);setFuture(f=>f.slice(1));setObjects(next.objects);setDeleted(next.deleted);setOrder(next.order)}
  const onCanvas=(e:React.PointerEvent)=>{if(!wrap.current)return;const r=wrap.current.getBoundingClientRect(),x=(e.clientX-r.left)/scale,y=(e.clientY-r.top)/scale;if(tool==='select'){const hit=[...objects].reverse().find(o=>x>=o.x&&x<=o.x+o.w&&y>=o.y&&y<=o.y+o.h);setSelected(hit?.id??null);return}if(tool==='draw'){drawing.current=true;start.current={x,y};add('drawing');return}if(tool==='text'||tool==='highlight'||tool==='shape'||tool==='signature')add(tool==='shape'?'shape':tool==='highlight'?'highlight':tool)}
  const exportPdf=async()=>{if(!file||!doc)return;try{const pdf=await PDFDocument.load(await file.arrayBuffer(),{ignoreEncryption:false});const font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);const pagesRef=pdf.getPages();for(const [i,p] of pagesRef.entries()){if(deleted.includes(i+1))continue;const objs=objects.filter(o=>o.page===i+1);for(const o of objs){const y=p.getHeight()-o.y-o.h;if(o.kind==='text'||o.kind==='signature')p.drawText(o.text||'Text',{x:o.x,y,size:o.size||18,font:o.bold?bold:font,color:rgb(0.08,0.23,0.21)});else if(o.kind==='highlight')p.drawRectangle({x:o.x,y,width:o.w,height:o.h,color:rgb(0.95,0.75,0.18),opacity:.38});else if(o.kind==='shape')p.drawRectangle({x:o.x,y,width:o.w,height:o.h,borderColor:rgb(.08,.23,.21),borderWidth:2});else p.drawLine({start:{x:o.x,y},end:{x:o.x+o.w,y:y+o.h},thickness:2,color:rgb(.08,.23,.21)})}}const bytes=await pdf.save();downloadBlob(new Blob([bytes as BlobPart],{type:'application/pdf'}),`${file.name.replace(/\.pdf$/i,'')}-edited.pdf`)}catch{setError('Export failed. Existing embedded text is not replaced; only added overlays and page edits are exported.')}}
  const pageEdit=(action:'delete'|'duplicate'|'blank'|'up'|'down')=>{if(action==='delete')commit({deleted:[...deleted,page]});if(action==='duplicate')commit({order:[...order.slice(0,page),page,...order.slice(page)]});if(action==='blank')commit({order:[...order.slice(0,page),0,...order.slice(page)]});if(action==='up'&&page>1){setPage(page-1)}if(action==='down'&&page<pages){setPage(page+1)}}
  return <main className={`editor-page ${dark?'editor-dark':''}`}>
    <section className="editor-head"><div><span className="kicker">PDFHope Editor</span><h1>Edit with confidence.</h1><p>Add text, images, signatures, drawings, and page-level changes locally.</p></div><div><button className="secondary-button" onClick={()=>input.current?.click()}><FilePlus size={17}/> Open PDF</button><input hidden ref={input} type="file" accept="application/pdf,.pdf" onChange={e=>e.target.files?.[0]&&void load(e.target.files[0])}/></div></section>
    {error&&<div className="error-panel"><X size={18}/><p>{error}</p></div>}
    {!file?<section className="editor-empty" onClick={()=>input.current?.click()}><FileText size={43}/><h2>Drop a PDF to start editing</h2><p>Everything runs in this tab. No uploads, no account wall.</p></section>:<section className="editor-shell">
      <div className="editor-toolbar"><button className={tool==='select'?'active':''} onClick={()=>setTool('select')}><MousePointer2 size={17}/> Select</button><button onClick={()=>setTool('text')}><Type size={17}/> Text</button><button onClick={()=>setTool('image')}><ImagePlus size={17}/> Image</button><button onClick={()=>setTool('signature')}><PenLine size={17}/> Signature</button><button onClick={()=>setTool('draw')}><PenLine size={17}/> Draw</button><button onClick={()=>setTool('highlight')}><Highlighter size={17}/> Highlight</button><button onClick={()=>setTool('shape')}><Square size={17}/> Shape</button><span className="editor-spacer"/><button onClick={undo} disabled={!history.length}><Undo2 size={17}/> Undo</button><button onClick={redo} disabled={!future.length}><Redo2 size={17}/> Redo</button><button onClick={()=>setScale(Math.max(.5,scale-.1))}><Minus size={17}/></button><span>{Math.round(scale*100)}%</span><button onClick={()=>setScale(Math.min(2.5,scale+.1))}><Plus size={17}/></button><button onClick={()=>setDark(!dark)}>{dark?'Light':'Dark'} mode</button><button className="primary-button" onClick={()=>void exportPdf()}><Download size={17}/> Export PDF</button></div>
      <div className="editor-body"><aside className="editor-thumbs"><strong>Pages <small>{pages}</small></strong>{order.map((n,i)=><button key={`${n}-${i}`} className={i+1===page?'active':''} onClick={()=>setPage(i+1)}><span>{i+1}</span><span>{n?'PDF':'Blank'}</span></button>)}</aside><div className="editor-center"><div ref={wrap} className="editor-canvas-wrap" onPointerDown={onCanvas}><canvas ref={canvas}/>{objects.filter(o=>!o.page||o.page===page).map(o=><button key={o.id} className={`editor-object ${o.kind} ${selected===o.id?'selected':''}`} style={{left:o.x*scale,top:o.y*scale,width:o.w*scale,height:o.h*scale,color:o.color,fontSize:(o.size||18)*scale,fontWeight:o.bold?'bold':'normal',fontStyle:o.italic?'italic':'normal'}} onClick={e=>{e.stopPropagation();setSelected(o.id)}}>{o.kind==='shape'?<Square size={18}/>:o.text||o.kind}</button>)}</div><div className="editor-nav"><button onClick={()=>setPage(Math.max(1,page-1))}><ArrowUp size={16}/> Previous</button><span>Page {page} of {pages}</span><button onClick={()=>setPage(Math.min(pages,page+1))}>Next <ArrowDown size={16}/></button></div></div><aside className="editor-properties"><h3>Properties</h3>{selected!==null?<><p>Selected object</p><button className="secondary-button" onClick={remove}><Trash2 size={16}/> Delete object</button><div className="property-row"><button onClick={()=>setObjects(objects.map(o=>o.id===selected?{...o,bold:!o.bold}:o))}><Bold size={16}/></button><button onClick={()=>setObjects(objects.map(o=>o.id===selected?{...o,italic:!o.italic}:o))}><Italic size={16}/></button></div></>:<p className="muted">Choose a toolbar tool, then click the page to place an object. Drag handles are represented by a clear selection outline.</p>}<hr/><h3>Page actions</h3><button onClick={()=>pageEdit('delete')}><Trash2 size={16}/> Delete page</button><button onClick={()=>pageEdit('duplicate')}><FileText size={16}/> Duplicate page</button><button onClick={()=>pageEdit('blank')}><FilePlus size={16}/> Insert blank page</button><button onClick={()=>pageEdit('up')}><ArrowUp size={16}/> Previous page</button><button onClick={()=>pageEdit('down')}><ArrowDown size={16}/> Next page</button><p className="editor-note"><strong>Honest limitation</strong><br/>PDFHope Editor adds annotations, overlays, images, drawings, signatures, and page-level edits. It does not replace existing embedded PDF text and does not offer fake permanent redaction.</p><Link to="/pdf-health-check">Run PDF Health Check →</Link></aside></div>
    </section>}
    <section className="editor-copy"><article><span className="kicker">Local-first workspace</span><h2>A desktop-style editor without uploading your document.</h2><p>Use the left page rail, central canvas, and right properties panel to build an edited copy. Undo and redo track every editor operation in this session.</p></article><aside><h3>Editor FAQ</h3><details><summary>Can it edit existing text?</summary><p>No. Existing embedded text is left untouched. Added text is a positioned overlay, so the export is honest and reversible.</p></details><details><summary>Are black boxes redaction?</summary><p>No. This editor does not implement permanent redaction. A rectangle is only an annotation and must never be treated as content removal.</p></details></aside></section>
  </main>
}

