import { Download, FileText, FolderOpen, Maximize, Minus, PanelLeft, Plus, Printer, RotateCw, Scan as Fit, Search, ShieldCheck, TableOfContents, X } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { openRenderedPdf } from '../lib/pdf/render'
import { downloadBlob, formatBytes } from '../lib/files'
import { useSeo } from '../hooks/useSeo'

type ReaderPage={number:number;width:number;height:number;text:string;matches:number}
export function PdfReader(){
  useSeo('PDF Reader — Read PDFs privately in your browser','Open, search, annotate, and print PDFs locally with a fast PDF reader. Your document stays on your device.','/pdf-reader')
  const [file,setFile]=useState<File|null>(null),[doc,setDoc]=useState<any>(null),[pages,setPages]=useState<ReaderPage[]>([]),[page,setPage]=useState(1),[scale,setScale]=useState(1),[continuous,setContinuous]=useState(true),[search,setSearch]=useState(''),[outline,setOutline]=useState<any[]>([]),[error,setError]=useState(''),[rot,setRot]=useState(0),[info,setInfo]=useState<any>(null),[sidebar,setSidebar]=useState(true)
  const inputRef=useRef<HTMLInputElement>(null),pageRefs=useRef<Record<number,HTMLDivElement|null>>({})
  const load=async(next:File)=>{setError('');setFile(next);try{const pdf=await openRenderedPdf(next);setDoc(pdf);const meta=await pdf.getMetadata().catch(()=>({info:{}}));const nextPages:ReaderPage[]=[];for(let n=1;n<=pdf.numPages;n+=1){const p=await pdf.getPage(n),v=p.getViewport({scale:1}),tc=await p.getTextContent();nextPages.push({number:n,width:v.width,height:v.height,text:tc.items.map((i:any)=>i.str).join(' '),matches:0})}setPages(nextPages);setInfo(meta.info||{});setPage(1);setScale(1);setOutline(await pdf.getOutline().catch(()=>[])||[])}catch(e){setError(/password|encrypted/i.test(String(e))?'This PDF is password-protected. Unlock it with permission before opening it.':'This PDF could not be opened. It may be corrupted or unsupported.')}}
  useEffect(()=>()=>{doc?.cleanup?.()},[doc])
  // Rendering is intentionally kept stable while the observer watches the current page nodes.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{if(!doc)return;const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){const n=Number((entry.target as HTMLElement).dataset.page);void render(n)}}),{rootMargin:'500px'});Object.values(pageRefs.current).forEach(el=>el&&observer.observe(el));return()=>observer.disconnect()},[doc,scale,continuous,rot])
  const canvases=useRef<Record<number,HTMLCanvasElement|null>>({}),textLayers=useRef<Record<number,HTMLDivElement|null>>({})
  const render=async(n:number)=>{if(!doc)return;const canvas=canvases.current[n],layer=textLayers.current[n];if(!canvas||!layer)return;const p=await doc.getPage(n),v=p.getViewport({scale:scale||1});canvas.width=Math.ceil(v.width);canvas.height=Math.ceil(v.height);canvas.style.transform=`rotate(${rot}deg)`;await p.render({canvasContext:canvas.getContext('2d')!,viewport:v}).promise;const tc=await p.getTextContent();layer.innerHTML='';layer.style.width=`${v.width}px`;layer.style.height=`${v.height}px`;tc.items.forEach((item:any)=>{const span=document.createElement('span');span.textContent=item.str+' ';span.style.position='absolute';const tx=item.transform;span.style.left=`${tx[4]*scale}px`;span.style.top=`${v.height-tx[5]*scale}px`;span.style.fontSize=`${Math.max(6,(item.height||10)*scale)}px`;span.style.transform='translateY(-100%)';span.style.color='transparent';span.style.whiteSpace='pre';if(search&&item.str.toLowerCase().includes(search.toLowerCase())){span.style.background='rgba(242,190,68,.55)';span.style.color='rgba(20,35,34,.2)'}layer.appendChild(span)})}
  const matches=pages.reduce((sum,p)=>sum+(search?p.text.toLowerCase().split(search.toLowerCase()).length-1:0),0)
  const go=(n:number)=>{const safe=Math.min(Math.max(1,n),pages.length||1);setPage(safe);pageRefs.current[safe]?.scrollIntoView({behavior:'smooth',block:'start'})}
  const onDrop=(e:React.DragEvent)=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f)void load(f)}
  return <main className="reader-page" onDragOver={e=>e.preventDefault()} onDrop={onDrop}>
    <section className="reader-head"><div><span className="kicker">PDFHope Reader</span><h1>Read PDFs with focus.</h1><p>Search, inspect, and print documents locally. Nothing is uploaded.</p></div><div className="reader-actions"><button className="secondary-button" onClick={()=>inputRef.current?.click()}><FolderOpen size={17}/> Open PDF</button><input ref={inputRef} hidden type="file" accept="application/pdf,.pdf" onChange={e=>e.target.files?.[0]&&void load(e.target.files[0])}/>{file&&<button className="secondary-button" onClick={()=>downloadBlob(file,file.name)}><Download size={17}/> Download original</button>}</div></section>
    {error&&<div className="error-panel"><X size={19}/><div><strong>Couldn’t open this PDF</strong><p>{error}</p></div></div>}
    {!file?<section className="reader-empty" onClick={()=>inputRef.current?.click()}><FileText size={42}/><h2>Drop a PDF here</h2><p>or choose a file from your device</p><small><ShieldCheck size={14}/> Processed on your device</small></section>:<section className="reader-shell">
      <div className="reader-toolbar"><button aria-label="Toggle thumbnails" onClick={()=>setSidebar(!sidebar)}><PanelLeft size={18}/></button><button onClick={()=>setContinuous(!continuous)}>{continuous?'Continuous':'Single page'}</button><button onClick={()=>setScale(Math.max(.45,scale-.15))} aria-label="Zoom out"><Minus size={17}/></button><span>{Math.round(scale*100)}%</span><button onClick={()=>setScale(Math.min(3,scale+.15))} aria-label="Zoom in"><Plus size={17}/></button><button onClick={()=>setScale(1)}><Fit size={17}/> Fit</button><label className="reader-page-jump">Page <input type="number" min="1" max={pages.length} value={page} onChange={e=>go(Number(e.target.value))}/> / {pages.length}</label><span className="reader-spacer"/><label className="reader-search"><Search size={16}/><input value={search} placeholder="Search text" onChange={e=>setSearch(e.target.value)}/>{search&&<small>{matches} match{matches===1?'':'es'}</small>}</label><button onClick={()=>setRot((rot+90)%360)} aria-label="Rotate view"><RotateCw size={17}/></button><button onClick={()=>window.print()} aria-label="Print"><Printer size={17}/></button><button onClick={()=>document.documentElement.requestFullscreen?.()} aria-label="Fullscreen"><Maximize size={17}/></button></div>
      <div className="reader-body">{sidebar&&<aside className="reader-sidebar"><div className="reader-sidebar-title"><strong>Pages</strong><span>{formatBytes(file.size)}</span></div>{pages.map(p=><button key={p.number} className={p.number===page?'active':''} onClick={()=>go(p.number)}><span>{p.number}</span><span className="thumb-placeholder">PDF</span></button>)}<details><summary><TableOfContents size={15}/> Outline</summary>{outline.length?<ul>{outline.map((item:any)=><li key={item.title}>{item.title}</li>)}</ul>:<small>No outline available</small>}</details><div className="reader-info"><strong>File information</strong><span>{file.name}</span><span>{pages.length} pages</span><span>{info?.Title||'No title metadata'}</span><Link to="/pdf-health-check">Run PDF Health Check →</Link></div></aside>}<div className={`reader-canvas ${continuous?'continuous':''}`}>{pages.map(p=><div key={p.number} className="reader-page-wrap" data-page={p.number} ref={el=>{pageRefs.current[p.number]=el}} onClick={()=>setPage(p.number)}><canvas ref={el=>{canvases.current[p.number]=el}}/><div className="reader-text-layer" ref={el=>{textLayers.current[p.number]=el}}/><span className="reader-page-label">Page {p.number}</span></div>)}</div></div>
    </section>}
    <section className="reader-copy"><article><span className="kicker">How it works</span><h2>A private reading room in your browser.</h2><p>PDF.js renders pages and text locally. Lazy intersection-based rendering keeps long documents responsive, including 100+ page files. Selectable text remains selectable when the source PDF provides it.</p></article><aside><h3>Reader FAQ</h3><details><summary>Can I edit existing PDF text?</summary><p>No. The reader is for reading and annotations; use PDF Editor for added overlays. Existing embedded text is never silently replaced.</p></details><details><summary>What about scanned PDFs?</summary><p>Scanned pages can be viewed, but search and text selection require an embedded text layer or OCR.</p></details></aside></section>
  </main>
}

