import { AlertCircle, ArrowLeft, Check, ChevronDown, ChevronUp, Download, Heart, LockKeyhole, RotateCcw, ShieldCheck, Trash2 } from 'lucide-react'
import { useEffect, useMemo, useRef, useState } from 'react'
import { Link, Navigate, useParams } from 'react-router-dom'
import { zipSync } from 'fflate'
import { FileDropzone } from '../components/FileDropzone'
import { ToolIcon } from '../components/ToolIcon'
import { PageGrid } from '../components/PageGrid'
import { getTool, tools } from '../data/tools'
import { downloadBlob, formatBytes, parsePageSelection, safeBaseName, validateFiles } from '../lib/files'
import { addPageNumbers, addWatermark, cleanMetadata, contactSheetPdf, copySelectedPages, deinterleavePdf, imagesToPdf, inspectPdf, interleavePdfs, jsonBlob, mergePdfs, nUpPdf, removePages, reorderPages, rotatePages, splitPdf } from '../lib/pdf/operations'
import { renderPdfPages, visualAnalysis } from '../lib/pdf/render'
import { useSeo } from '../hooks/useSeo'

type Phase = 'upload'|'configure'|'processing'|'done'

export function ToolPage() {
  const { slug='' }=useParams(),tool=getTool(slug)
  if(!tool)return <Navigate to="/404" replace/>
  return <ToolWorkspace key={tool.slug} tool={tool}/>
}

function ToolWorkspace({tool}:{tool:NonNullable<ReturnType<typeof getTool>>}) {
  useSeo(tool.name,tool.description,`/${tool.slug}`)
  const [files,setFiles]=useState<File[]>([]),[phase,setPhase]=useState<Phase>('upload'),[error,setError]=useState(''),[progress,setProgress]=useState(0),[result,setResult]=useState<Blob|null>(null),[resultName,setResultName]=useState(tool.output),[report,setReport]=useState<Record<string,unknown>|null>(null),[pageCount,setPageCount]=useState(0),[selected,setSelected]=useState<number[]>([]),[order,setOrder]=useState<number[]>([]),[range,setRange]=useState(''),[splitMode,setSplitMode]=useState<'every'|'ranges'|'interval'>('every'),[interval,setInterval]=useState(2),[angle,setAngle]=useState(90),[favorite,setFavorite]=useState(()=>JSON.parse(localStorage.getItem('pdfhope-favorites')||'[]').includes(tool.slug)),[options,setOptions]=useState({pageSize:'a4',margin:24,fit:'fit',format:tool.slug.includes('png')?'png':'jpeg',quality:.86,scale:1.6,start:1,size:12,position:'bottom-center',prefix:'',text:'CONFIDENTIAL',opacity:.2,watermarkAngle:-32,nup:2,landscape:false,columns:3})
  const needsPages=!['merge','images-to-pdf','interleave'].includes(tool.kind)
  const isAnalyzer=['health','blank','page-size','orientation','duplicate'].includes(tool.kind)
  useEffect(()=>{const recent:string[]=JSON.parse(localStorage.getItem('pdfhope-recent')||'[]');localStorage.setItem('pdfhope-recent',JSON.stringify([tool.slug,...recent.filter((value)=>value!==tool.slug)].slice(0,6)))},[tool.slug])
  const mergeInput=useRef<HTMLInputElement>(null)
  const acceptFiles=async(next:File[])=>{try{const incoming=tool.kind==='merge'&&phase==='configure'?[...files,...next]:next;validateFiles(incoming,tool.kind!=='images-to-pdf',Boolean(tool.multiple));setError('');setFiles(incoming);setPhase('configure');setResult(null);setReport(null);if(needsPages&&incoming[0]){const info=await inspectPdf(incoming[0]);setPageCount(info.pageCount);setSelected([]);setOrder(Array.from({length:info.pageCount},(_,index)=>index))}}catch(cause){setError(cause instanceof Error?cause.message:'The file could not be opened.')}}
  const updateFavorite=()=>{const stored:string[]=JSON.parse(localStorage.getItem('pdfhope-favorites')||'[]');const next=favorite?stored.filter((value)=>value!==tool.slug):[...new Set([...stored,tool.slug])];localStorage.setItem('pdfhope-favorites',JSON.stringify(next));setFavorite(!favorite)}
  const reset=()=>{setFiles([]);setPhase('upload');setError('');setResult(null);setReport(null);setProgress(0);setPageCount(0);setSelected([]);setRange('')}
  const pages=()=>selected.length?selected:parsePageSelection(range,pageCount)
  const process=async()=>{if(tool.kind==='merge'&&files.length<2){setError('Please add at least two PDF files to merge.');return}setError('');setPhase('processing');setProgress(12);setResult(null);setReport(null);try{let output:Blob|null=null,name=tool.output;const first=files[0];setProgress(28)
    switch(tool.kind){
      case'merge':output=await mergePdfs(files);break
      case'extract':output=await copySelectedPages(first,pages());break
      case'delete':output=await removePages(first,pages());break
      case'reorder':output=await reorderPages(first,order);break
      case'rotate':output=await rotatePages(first,pages(),angle);break
      case'split':{let groups:number[][]=[];if(splitMode==='every')groups=Array.from({length:pageCount},(_,index)=>[index]);else if(splitMode==='interval')for(let start=0;start<pageCount;start+=interval)groups.push(Array.from({length:Math.min(interval,pageCount-start)},(_,offset)=>start+offset));else groups=range.split(';').filter(Boolean).map((value)=>parsePageSelection(value,pageCount));if(!groups.length)throw new Error('Enter at least one page range.');output=await splitPdf(first,groups);break}
      case'images-to-pdf':output=await imagesToPdf(files,{pageSize:options.pageSize as 'auto'|'a4'|'letter',margin:Number(options.margin),fit:options.fit as 'fit'|'fill'});break
      case'pdf-to-image':{const rendered=await renderPdfPages(first,{pages:pages(),format:options.format as 'jpeg'|'png',quality:Number(options.quality),scale:Number(options.scale)});if(rendered.length===1){output=new Blob([rendered[0].bytes as BlobPart],{type:`image/${options.format}`});name=rendered[0].name}else output=new Blob([zipSync(Object.fromEntries(rendered.map((item)=>[item.name,item.bytes]))) as BlobPart],{type:'application/zip'});break}
      case'page-numbers':output=await addPageNumbers(first,{selected:pages(),start:Number(options.start),size:Number(options.size),position:String(options.position),prefix:String(options.prefix)});break
      case'watermark':if(!String(options.text).trim())throw new Error('Enter watermark text.');output=await addWatermark(first,{selected:pages(),text:String(options.text),size:Number(options.size)*3,angle:Number(options.watermarkAngle),opacity:Number(options.opacity)});break
      case'metadata':{const cleaned=await cleanMetadata(first);output=cleaned.output;setReport(cleaned.report);break}
      case'interleave':output=await interleavePdfs(files);break
      case'deinterleave':output=await deinterleavePdf(first);break
      case'n-up':output=await nUpPdf(first,Number(options.nup) as 2|4,Boolean(options.landscape));break
      case'contact-sheet':output=await contactSheetPdf(first,Number(options.columns) as 2|3|4);break
      case'health':case'blank':case'page-size':case'orientation':case'duplicate':{const info=await inspectPdf(first);let analysis:Awaited<ReturnType<typeof visualAnalysis>>|null=null;if(['health','blank','duplicate'].includes(tool.kind))analysis=await visualAnalysis(first);const portrait=info.pages.filter((page)=>page.orientation==='Portrait').length,landscape=info.pages.filter((page)=>page.orientation==='Landscape').length,custom=info.pages.filter((page)=>page.size==='Custom').map((page)=>page.page),scanned=analysis?.pages.filter((page)=>page.textItems===0).map((page)=>page.page)??[];const score=Math.max(0,100-Math.min(25,custom.length*5)-Math.min(25,scanned.length/info.pageCount*25)-Math.min(25,(analysis?.blankCandidates.length??0)*5)-Math.min(15,(analysis?.duplicates.length??0)*3));const full={...info,orientation:{portrait,landscape},unusualPageSizes:custom,likelyScannedPages:scanned,blankCandidates:analysis?.blankCandidates??[],duplicateCandidates:analysis?.duplicates??[],healthScore:Math.round(score),scoring:'Starts at 100; deductions apply for custom sizes, image-only pages, blank candidates, and duplicate candidates. This is a usability heuristic, not document certification.'};const filtered=tool.kind==='blank'?{fileName:info.fileName,pageCount:info.pageCount,blankCandidates:full.blankCandidates,method:'Pages with over 99.2% near-white pixels and no detected text are flagged.'}:tool.kind==='duplicate'?{fileName:info.fileName,pageCount:info.pageCount,duplicateCandidates:full.duplicateCandidates,method:'16×16 average perceptual hashes; pairs at 94% or higher similarity are shown.'}:tool.kind==='page-size'?{fileName:info.fileName,pages:info.pages,mixedSizes:new Set(info.pages.map((page)=>`${page.width}x${page.height}`)).size>1}:tool.kind==='orientation'?{fileName:info.fileName,...full.orientation,pages:info.pages.map(({page,orientation})=>({page,orientation}))}:full;setReport(filtered as Record<string,unknown>);output=jsonBlob(filtered);break}
    }
    setProgress(100);setResult(output);setResultName(`${safeBaseName(files[0]?.name||'document')}-${name}`);setPhase('done')
  }catch(cause){setError(cause instanceof Error?friendlyError(cause):'Processing failed.');setPhase('configure')}}
  const related=useMemo(()=>tools.filter((item)=>item.category===tool.category&&item.slug!==tool.slug).slice(0,3),[tool])
  return <main className="tool-page"><div className="tool-breadcrumb"><Link to="/tools"><ArrowLeft size={16}/> All tools</Link><span>/</span><span>{tool.category}</span></div><section className="tool-intro"><div><span className="tool-brand-label"><ToolIcon slug={tool.slug} compact/><span className="kicker">{tool.category}</span></span><h1>{tool.name}</h1><p>{tool.description}</p></div><button className={`favorite-button ${favorite?'active':''}`} onClick={updateFavorite} aria-label={favorite?'Remove from favorites':'Add to favorites'}><Heart size={18} fill={favorite?'currentColor':'none'}/>{favorite?'Saved':'Save tool'}</button></section>
    <ol className="stepper" aria-label="Progress"><li className={phase==='upload'?'active':'complete'}><span>1</span>Upload</li><li className={phase==='configure'?'active':phase==='processing'||phase==='done'?'complete':''}><span>2</span>Configure</li><li className={phase==='processing'||phase==='done'?'active':''}><span>3</span>Process & download</li></ol>
    {error&&<div className="error-panel" role="alert"><AlertCircle size={20}/><div><strong>We couldn’t continue</strong><p>{error}</p></div></div>}
    <section className="workspace-card">
      {phase==='upload'&&<FileDropzone accept={tool.accepts} multiple={tool.multiple} onFiles={acceptFiles}/>} 
      {(phase==='configure'||phase==='processing')&&<><FileQueue files={files} setFiles={setFiles} canReorder={Boolean(tool.multiple)} onAddFiles={tool.kind==='merge'?acceptFiles:undefined}/>{tool.kind==='merge'&&<><input ref={mergeInput} type="file" accept="application/pdf" multiple hidden onChange={(event)=>{acceptFiles(Array.from(event.target.files??[]));event.currentTarget.value='' }}/><button className="secondary-button add-more-button" disabled={phase==='processing'} onClick={()=>mergeInput.current?.click()}>Add More PDFs</button>{files.length<2&&<p className="setting-note">Add at least one more PDF to merge.</p>}</>}<div className="configure-panel"><div className="configure-title"><div><span className="step-label">Step 2</span><h2>Choose your settings</h2></div><button className="text-button" onClick={reset}><Trash2 size={16}/> Clear all</button></div><ToolControls file={files[0]} tool={tool} pageCount={pageCount} selected={selected} setSelected={setSelected} order={order} setOrder={setOrder} range={range} setRange={setRange} splitMode={splitMode} setSplitMode={setSplitMode} interval={interval} setInterval={setInterval} angle={angle} setAngle={setAngle} options={options} setOptions={setOptions}/><div className="process-bar"><span><LockKeyhole size={16}/> Runs locally in this tab</span><button className="primary-button" disabled={phase==='processing'||(tool.kind==='merge'&&files.length<2)} onClick={process}>{phase==='processing'?`Processing… ${progress}%`:tool.kind==='merge'?'Merge PDFs':`${isAnalyzer?'Analyze':'Process'} ${files.length>1?`${files.length} files`:''}`}</button></div></div></>}
      {phase==='done'&&<div className="result-panel"><span className="success-icon"><Check size={30}/></span><span className="kicker">Complete</span><h2>{isAnalyzer?'Your report is ready':'Your file is ready'}</h2><p>Processing finished locally. Nothing was sent to PDFHope.</p>{report&&<ReportView report={report}/>} {result&&<button className="primary-button download-button" onClick={()=>downloadBlob(result,resultName)}><Download size={19}/> Download {isAnalyzer?'report':'file'}</button>}<button className="secondary-button" onClick={reset}><RotateCcw size={17}/> Start over</button></div>}
    </section>
    <section className="tool-copy"><article><span className="kicker">How it works</span><h2>Simple, local, predictable</h2><ol>{tool.instructions.map((item,index)=><li key={item}><span>{index+1}</span><p>{item}</p></li>)}</ol></article><aside><ShieldCheck size={24}/><h3>Privacy for this tool</h3><p>Selected files are read by browser APIs and processed in memory on your device. This page has no file-upload endpoint.</p><h3>Limitations</h3><p>{tool.limitations}</p></aside></section>
    <section className="faq"><span className="kicker">Questions</span><h2>{tool.name} FAQ</h2><details><summary>Are my files uploaded?</summary><p>No. This implementation processes supported files in your browser. Network requests may still load the website’s code, but your document bytes are not sent to PDFHope.</p></details><details><summary>Why can a large PDF fail?</summary><p>Browsers have device-dependent memory limits. Close other heavy tabs, try a smaller document, or process fewer pages at once.</p></details><details><summary>Does the original file change?</summary><p>No. PDFHope creates a new downloadable file and does not modify the original on your device.</p></details></section>
    <section className="related"><h2>Related {tool.category.toLowerCase()} tools</h2><div>{related.map((item)=><Link key={item.slug} to={`/${item.slug}`}><ToolIcon slug={item.slug} compact/><span><strong>{item.name}</strong><small>{item.short}</small></span></Link>)}</div></section>
  </main>
}

function FileQueue({files,setFiles,canReorder,onAddFiles}:{files:File[];setFiles:(files:File[])=>void;canReorder:boolean;onAddFiles?: (files:File[])=>void}){const move=(from:number,to:number)=>{if(from===to||to<0||to>=files.length)return;const next=[...files],item=next.splice(from,1)[0];next.splice(to,0,item);setFiles(next)};return <div className="file-queue" onDragOver={(event)=>{if(onAddFiles&&event.dataTransfer.types.includes('Files'))event.preventDefault()}} onDrop={(event)=>{if(onAddFiles&&event.dataTransfer.files.length){event.preventDefault();onAddFiles(Array.from(event.dataTransfer.files))}}}>{files.map((file,index)=><div className="file-card" key={`${file.name}-${file.lastModified}-${index}`} draggable={canReorder} onDragStart={(event)=>event.dataTransfer.setData('text/plain',String(index))} onDragOver={(event)=>event.preventDefault()} onDrop={(event)=>{if(event.dataTransfer.files.length)return;move(Number(event.dataTransfer.getData('text/plain')),index)}}><span className="pdf-badge">PDF</span><span><strong>{file.name}</strong><small>{formatBytes(file.size)}{canReorder?' · drag to reorder':''}</small></span>{canReorder&&<span className="file-order-controls"><button disabled={index===0} onClick={()=>move(index,index-1)} aria-label={`Move ${file.name} up`}><ChevronUp size={16}/></button><button disabled={index===files.length-1} onClick={()=>move(index,index+1)} aria-label={`Move ${file.name} down`}><ChevronDown size={16}/></button></span>}<button onClick={()=>setFiles(files.filter((_,item)=>item!==index))} aria-label={`Remove ${file.name}`}><Trash2 size={17}/></button></div>)}</div>}

type Options={pageSize:string;margin:number;fit:string;format:string;quality:number;scale:number;start:number;size:number;position:string;prefix:string;text:string;opacity:number;watermarkAngle:number;nup:number;landscape:boolean;columns:number}
function ToolControls({file,tool,pageCount,selected,setSelected,order,setOrder,range,setRange,splitMode,setSplitMode,interval,setInterval,angle,setAngle,options,setOptions}:{file:File;tool:NonNullable<ReturnType<typeof getTool>>;pageCount:number;selected:number[];setSelected:(value:number[])=>void;order:number[];setOrder:(value:number[])=>void;range:string;setRange:(value:string)=>void;splitMode:'every'|'ranges'|'interval';setSplitMode:(value:'every'|'ranges'|'interval')=>void;interval:number;setInterval:(value:number)=>void;angle:number;setAngle:(value:number)=>void;options:Options;setOptions:(value:Options)=>void}){
  const update=(key:keyof Options,value:Options[keyof Options])=>setOptions({...options,[key]:value})
  if(tool.kind==='merge'||tool.kind==='interleave')return <p className="setting-note">The files will be combined in the order shown above. Drag cards to change the order.</p>
  if(tool.kind==='images-to-pdf')return <div className="control-grid"><Select label="Page size" value={options.pageSize} onChange={(value)=>update('pageSize',value)} choices={[['a4','A4'],['letter','Letter'],['auto','Match image']]}/><Select label="Image fit" value={options.fit} onChange={(value)=>update('fit',value)} choices={[['fit','Fit — show all'],['fill','Fill — may crop']]}/><NumberField label="Margin (pt)" value={options.margin} min={0} max={72} onChange={(value)=>update('margin',value)}/></div>
  if(tool.kind==='split')return <div className="control-stack"><Select label="Split mode" value={splitMode} onChange={(value)=>setSplitMode(value as typeof splitMode)} choices={[['every','Every page'],['ranges','Custom groups'],['interval','Every N pages']]}/>{splitMode==='ranges'&&<TextField label="Groups separated by semicolons" value={range} placeholder="1-3; 4-6; 8,10" onChange={setRange}/>} {splitMode==='interval'&&<NumberField label="Pages per file" value={interval} min={1} max={pageCount} onChange={setInterval}/>}</div>
  if(tool.kind==='pdf-to-image')return <div className="control-grid"><TextField label="Pages (blank means all)" value={range} placeholder="1, 3, 5-8" onChange={setRange}/><Select label="Resolution" value={String(options.scale)} onChange={(value)=>update('scale',Number(value))} choices={[["1","Standard"],["1.6","High"],["2.2","Very high"]]}/>{options.format==='jpeg'&&<label className="field"><span>JPG quality · {Math.round(Number(options.quality)*100)}%</span><input type="range" min="0.5" max="1" step=".05" value={options.quality} onChange={(event)=>update('quality',Number(event.target.value))}/></label>}</div>
  if(tool.kind==='page-numbers')return <><div className="control-grid"><TextField label="Pages" value={range} placeholder="Blank means all pages" onChange={setRange}/><NumberField label="Starting number" value={options.start} min={0} max={99999} onChange={(value)=>update('start',value)}/><NumberField label="Font size" value={options.size} min={8} max={48} onChange={(value)=>update('size',value)}/><Select label="Position" value={options.position} onChange={(value)=>update('position',value)} choices={[["bottom-left","Bottom left"],["bottom-center","Bottom center"],["bottom-right","Bottom right"],["top-left","Top left"],["top-center","Top center"],["top-right","Top right"]]}/><TextField label="Prefix (optional)" value={options.prefix} placeholder="Page " onChange={(value)=>update('prefix',value)}/></div></>
  if(tool.kind==='watermark')return <div className="control-grid"><TextField label="Watermark text" value={options.text} onChange={(value)=>update('text',value)}/><TextField label="Pages" value={range} placeholder="Blank means all pages" onChange={setRange}/><NumberField label="Angle" value={options.watermarkAngle} min={-90} max={90} onChange={(value)=>update('watermarkAngle',value)}/><label className="field"><span>Opacity · {Math.round(Number(options.opacity)*100)}%</span><input type="range" min=".05" max=".8" step=".05" value={options.opacity} onChange={(event)=>update('opacity',Number(event.target.value))}/></label></div>
  if(tool.kind==='rotate')return <><div className="control-grid"><TextField label="Pages" value={range} placeholder="Blank means all pages" onChange={setRange}/><Select label="Rotation" value={String(angle)} onChange={(value)=>setAngle(Number(value))} choices={[["90","90° clockwise"],["180","180°"],["270","270° clockwise"]]}/></div><PageGrid file={file} pages={pageCount} selected={selected} onSelected={setSelected}/></>
  if(tool.kind==='reorder')return <PageGrid file={file} pages={pageCount} selected={[]} order={order} onOrder={setOrder}/>
  if(tool.kind==='extract'||tool.kind==='delete')return <><TextField label={tool.kind==='delete'?'Pages to remove':'Pages to extract'} value={range} placeholder="1, 3, 5-8" onChange={setRange}/><PageGrid file={file} pages={pageCount} selected={selected} onSelected={setSelected}/></>
  if(tool.kind==='n-up')return <div className="control-grid"><Select label="Pages per sheet" value={String(options.nup)} onChange={(value)=>update('nup',Number(value))} choices={[["2","2 pages"],["4","4 pages"]]}/><Select label="Sheet orientation" value={options.landscape?'landscape':'portrait'} onChange={(value)=>update('landscape',value==='landscape')} choices={[["portrait","Portrait A4"],["landscape","Landscape A4"]]}/></div>
  if(tool.kind==='contact-sheet')return <Select label="Columns" value={String(options.columns)} onChange={(value)=>update('columns',Number(value))} choices={[["2","2 columns"],["3","3 columns"],["4","4 columns"]]}/>
  if(['health','blank','page-size','orientation','duplicate','metadata','deinterleave'].includes(tool.kind))return <p className="setting-note">Ready to process {pageCount.toLocaleString()} page{pageCount===1?'':'s'}. The analysis runs locally and may take longer for large documents.</p>
  return null
}
function TextField({label,value,onChange,placeholder=''}:{label:string;value:string;onChange:(value:string)=>void;placeholder?:string}){return <label className="field"><span>{label}</span><input value={value} placeholder={placeholder} onChange={(event)=>onChange(event.target.value)}/></label>}
function NumberField({label,value,onChange,min,max}:{label:string;value:number;onChange:(value:number)=>void;min:number;max:number}){return <label className="field"><span>{label}</span><input type="number" value={value} min={min} max={max} onChange={(event)=>onChange(Number(event.target.value))}/></label>}
function Select({label,value,onChange,choices}:{label:string;value:string;onChange:(value:string)=>void;choices:string[][]}){return <label className="field"><span>{label}</span><select value={value} onChange={(event)=>onChange(event.target.value)}>{choices.map(([key,name])=><option value={key} key={key}>{name}</option>)}</select></label>}
function ReportView({report}:{report:Record<string,unknown>}){return <div className="report-view">{Object.entries(report).slice(0,9).map(([key,value])=><div key={key}><span>{key.replace(/([A-Z])/g,' $1')}</span><strong>{typeof value==='object'?Array.isArray(value)?value.length?JSON.stringify(value):'None':value?`${Object.keys(value as object).length} fields`:'None':String(value)}</strong></div>)}</div>}
function friendlyError(error:Error){if(/encrypted|password/i.test(error.message))return 'This PDF is password-protected. Remove the password with permission before using this tool.';if(/header|catalog|parse|invalid/i.test(error.message))return 'This file appears to be corrupted or is not a valid PDF.';return error.message||'Processing failed. Try a smaller file or reload the page.'}
