import { AlertCircle, ArrowLeft, Check, ChevronDown, ChevronUp, Download, Heart, LockKeyhole, RotateCcw, Trash2 } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { Link, Navigate, useParams } from 'react-router-dom'
import { zipSync } from 'fflate'
import { FileDropzone } from '../components/FileDropzone'
import { ToolIcon } from '../components/ToolIcon'
import { PageGrid } from '../components/PageGrid'
import { getTool } from '../data/tools'
import { downloadBlob, formatBytes, parsePageSelection, safeBaseName, validateFiles } from '../lib/files'
import { addPageNumbers, addWatermark, cleanMetadata, contactSheetPdf, copySelectedPages, deinterleavePdf, imagesToPdf, inspectPdf, interleavePdfs, jsonBlob, mergePdfs, nUpPdf, removePages, reorderPages, rotatePages, splitPdf } from '../lib/pdf/operations'
import { renderPdfPages, visualAnalysis } from '../lib/pdf/render'
import { useSeo } from '../hooks/useSeo'
import { toolSeo } from '../data/toolSeo'
import { ToolSeoContent } from '../components/ToolSeoContent'
import { compressPdf, DEFAULT_COMPRESSION_PRESET, type CompressionPreset, type CompressionProgress, type CompressionResult } from '../lib/pdf/compress'

type Phase = 'upload'|'configure'|'processing'|'done'

export function ToolPage() {
  const { slug='' }=useParams(),tool=getTool(slug)
  if(!tool)return <Navigate to="/404" replace/>
  return <ToolWorkspace key={tool.slug} tool={tool}/>
}

function ToolWorkspace({tool}:{tool:NonNullable<ReturnType<typeof getTool>>}) {
  const seo = toolSeo[tool.slug]
  useSeo(seo?.seoTitle||tool.name,seo?.metaDescription||tool.description,`/${tool.slug}`,true,true)
  const [files,setFiles]=useState<File[]>([]),[phase,setPhase]=useState<Phase>('upload'),[error,setError]=useState(''),[progress,setProgress]=useState(0),[result,setResult]=useState<Blob|null>(null),[resultName,setResultName]=useState(tool.output),[report,setReport]=useState<Record<string,unknown>|null>(null),[pageCount,setPageCount]=useState(0),[selected,setSelected]=useState<number[]>([]),[order,setOrder]=useState<number[]>([]),[range,setRange]=useState(''),[splitMode,setSplitMode]=useState<'every'|'ranges'|'interval'>('every'),[interval,setInterval]=useState(2),[angle,setAngle]=useState(90),[favorite,setFavorite]=useState(()=>JSON.parse(localStorage.getItem('pdfhope-favorites')||'[]').includes(tool.slug)),[options,setOptions]=useState({pageSize:'a4',margin:24,fit:'fit',format:tool.slug.includes('png')?'png':'jpeg',quality:.86,scale:1.6,start:1,size:12,position:'bottom-center',prefix:'',text:'CONFIDENTIAL',opacity:.2,watermarkAngle:-32,nup:2,landscape:false,columns:3})
  const [compressionPreset,setCompressionPreset]=useState<CompressionPreset>(DEFAULT_COMPRESSION_PRESET),[compressionProgress,setCompressionProgress]=useState<CompressionProgress|null>(null),[compressionResult,setCompressionResult]=useState<CompressionResult|null>(null)
  const needsPages=!['merge','images-to-pdf','interleave'].includes(tool.kind)
  const isAnalyzer=['health','blank','page-size','orientation','duplicate'].includes(tool.kind)
  useEffect(()=>{const recent:string[]=JSON.parse(localStorage.getItem('pdfhope-recent')||'[]');localStorage.setItem('pdfhope-recent',JSON.stringify([tool.slug,...recent.filter((value)=>value!==tool.slug)].slice(0,6)))},[tool.slug])
  const mergeInput=useRef<HTMLInputElement>(null)
  const acceptFiles=async(next:File[])=>{try{const incoming=tool.kind==='merge'&&phase==='configure'?[...files,...next]:next;validateFiles(incoming,tool.kind!=='images-to-pdf',Boolean(tool.multiple));setError('');setFiles(incoming);setPhase('configure');setResult(null);setReport(null);setCompressionResult(null);if(needsPages&&incoming[0]){const info=await inspectPdf(incoming[0]);setPageCount(info.pageCount);setSelected([]);setOrder(Array.from({length:info.pageCount},(_,index)=>index))}}catch(cause){setError(cause instanceof Error?cause.message:'The file could not be opened.')}}
  const updateFavorite=()=>{const stored:string[]=JSON.parse(localStorage.getItem('pdfhope-favorites')||'[]');const next=favorite?stored.filter((value)=>value!==tool.slug):[...new Set([...stored,tool.slug])];localStorage.setItem('pdfhope-favorites',JSON.stringify(next));setFavorite(!favorite)}
  const reset=()=>{setFiles([]);setPhase('upload');setError('');setResult(null);setReport(null);setCompressionResult(null);setCompressionProgress(null);setCompressionPreset(DEFAULT_COMPRESSION_PRESET);setProgress(0);setPageCount(0);setSelected([]);setRange('')}
  const pages=()=>selected.length?selected:parsePageSelection(range,pageCount)
  const process=async()=>{if(tool.kind==='merge'&&files.length<2){setError('Please add at least two PDF files to merge.');return}setError('');setPhase('processing');setProgress(12);setResult(null);setReport(null);setCompressionResult(null);try{let output:Blob|null=null,name=tool.output;const first=files[0];if(tool.kind!=='compress')setProgress(28)
    switch(tool.kind){
      case'compress':{const compressed=await compressPdf(first,{preset:compressionPreset,onProgress:setCompressionProgress});setCompressionResult(compressed);output=compressed.output;name='compressed.pdf';break}
      case'merge':output=await mergePdfs(files);break
      case'extract':output=await copySelectedPages(first,pages());break
      case'delete':output=await removePages(first,pages());break
      case'reorder':output=await reorderPages(first,order);break
      case'rotate':output=await rotatePages(first,pages(),angle);break
      case'split':{let groups:number[][]=[];if(splitMode==='every')groups=Array.from({length:pageCount},(_,index)=>[index]);else if(splitMode==='interval')for(let start=0;start<pageCount;start+=interval)groups.push(Array.from({length:Math.min(interval,pageCount-start)},(_,offset)=>start+offset));else groups=range.split(';').filter(Boolean).map((value)=>parsePageSelection(value,pageCount));if(!groups.length)throw new Error('Enter at least one page range.');output=await splitPdf(first,groups);break}
      case'images-to-pdf':output=await imagesToPdf(files,{pageSize:options.pageSize as 'auto'|'a4'|'letter',margin:Number(options.margin),fit:options.fit as 'fit'|'fill'});break
      case'pdf-to-image':{const rendered=await renderPdfPages(first,{pages:pages(),format:options.format as 'jpeg'|'png',quality:Number(options.quality),scale:Number(options.scale)});if(rendered.length===1){output=new Blob([rendered[0].bytes as BlobPart],{type:`image/${options.format}`});name=rendered[0].name}else output=new Blob([zipSync(Object.fromEntries(rendered.map((item)=>[item.name,item.bytes]))) as BlobPart],{type:'application/zip'});break}
      case'page-numbers':output=await addPageNumbers(first,{selected:pages(),start:Number(options.start),size:Number(options.size),position:String(options.position),prefix:String(options.prefix)});break
      case'watermark':if(!String(options.text).trim())throw new Error('Enter watermark text.');output=await addWatermark(first,{selected:pages(),text:String(options.text),size:Number(options.size)*3,angle:Number(options.watermarkAngle),opacity:Number(options.opacity)});break
      case'metadata':{const cleaned=await cleanMetadata(first);output=cleaned.output;setReport(cleaned.report);break}
      case'interleave':output=await interleavePdfs(files);break
      case'deinterleave':output=await deinterleavePdf(first);break
      case'n-up':output=await nUpPdf(first,Number(options.nup) as 2|4,Boolean(options.landscape));break
      case'contact-sheet':output=await contactSheetPdf(first,Number(options.columns) as 2|3|4);break
      case'health':case'blank':case'page-size':case'orientation':case'duplicate':{const info=await inspectPdf(first);let analysis:Awaited<ReturnType<typeof visualAnalysis>>|null=null;if(['health','blank','duplicate'].includes(tool.kind))analysis=await visualAnalysis(first);const portrait=info.pages.filter((page)=>page.orientation==='Portrait').length,landscape=info.pages.filter((page)=>page.orientation==='Landscape').length,custom=info.pages.filter((page)=>page.size==='Custom').map((page)=>page.page),scanned=analysis?.pages.filter((page)=>page.textItems===0).map((page)=>page.page)??[];const score=Math.max(0,100-Math.min(25,custom.length*5)-Math.min(25,scanned.length/info.pageCount*25)-Math.min(25,(analysis?.blankCandidates.length??0)*5)-Math.min(15,(analysis?.duplicates.length??0)*3));const full={...info,orientation:{portrait,landscape},unusualPageSizes:custom,likelyScannedPages:scanned,blankCandidates:analysis?.blankCandidates??[],duplicateCandidates:analysis?.duplicates??[],healthScore:Math.round(score),scoring:'Starts at 100; deductions apply for custom sizes, image-only pages, blank candidates, and duplicate candidates. This is a usability heuristic, not document certification.'};const filtered=tool.kind==='blank'?{fileName:info.fileName,pageCount:info.pageCount,blankCandidates:full.blankCandidates,method:'Pages with over 99.2% near-white pixels and no detected text are flagged.'}:tool.kind==='duplicate'?{fileName:info.fileName,pageCount:info.pageCount,duplicateCandidates:full.duplicateCandidates,method:'16×16 average perceptual hashes; pairs at 94% or higher similarity are shown.'}:tool.kind==='page-size'?{fileName:info.fileName,pages:info.pages,mixedSizes:new Set(info.pages.map((page)=>`${page.width}x${page.height}`)).size>1}:tool.kind==='orientation'?{fileName:info.fileName,...full.orientation,pages:info.pages.map(({page,orientation})=>({page,orientation}))}:full;setReport(filtered as Record<string,unknown>);output=jsonBlob(filtered);break}
    }
    setProgress(100);setResult(output);setResultName(`${safeBaseName(files[0]?.name||'document')}-${name}`);setPhase('done')
  }catch(cause){setError(cause instanceof Error?friendlyError(cause):'Processing failed.');setPhase('configure')}}
  return <main className="tool-page"><div className="tool-breadcrumb"><Link to="/tools"><ArrowLeft size={16}/> All tools</Link><span>/</span><span>{tool.category}</span></div><section className="tool-intro"><div className="tool-intro-copy"><div className="tool-title-row"><ToolIcon slug={tool.slug} compact/><h1>{tool.name}</h1></div><p>{tool.description}</p></div><button className={`favorite-button ${favorite?'active':''}`} onClick={updateFavorite} aria-label={favorite?'Remove from favorites':'Add to favorites'}><Heart size={18} fill={favorite?'currentColor':'none'}/>{favorite?'Saved':'Save tool'}</button></section>
    {phase!=='upload'&&<ol className="stepper" aria-label="Progress"><li className="complete"><span>1</span>Upload</li><li className={phase==='configure'?'active':phase==='processing'||phase==='done'?'complete':''}><span>2</span>Configure</li><li className={phase==='processing'||phase==='done'?'active':''}><span>3</span>Process & download</li></ol>}
    {error&&<div className="error-panel" role="alert"><AlertCircle size={20}/><div><strong>We couldn’t continue</strong><p>{error}</p></div></div>}
    <section className={`workspace-card${phase==='upload'?' workspace-card--empty':''}`}>
      {phase==='upload'&&<FileDropzone accept={tool.accepts} multiple={tool.multiple} onFiles={acceptFiles}/>} 
      {(phase==='configure'||phase==='processing')&&<><FileQueue files={files} setFiles={setFiles} canReorder={Boolean(tool.multiple)} onAddFiles={tool.kind==='merge'?acceptFiles:undefined}/>{tool.kind==='merge'&&<><input ref={mergeInput} type="file" accept="application/pdf" multiple hidden onChange={(event)=>{acceptFiles(Array.from(event.target.files??[]));event.currentTarget.value='' }}/><button className="secondary-button add-more-button" disabled={phase==='processing'} onClick={()=>mergeInput.current?.click()}>Add More PDFs</button>{files.length<2&&<p className="setting-note">Add at least one more PDF to merge.</p>}</>}<div className="configure-panel"><div className="configure-title"><div><span className="step-label">Step 2</span><h2>Choose your settings</h2></div><button className="text-button" onClick={reset} disabled={phase==='processing'}><Trash2 size={16}/> Clear all</button></div>{tool.kind==='compress'?<CompressionControls file={files[0]} pageCount={pageCount} preset={compressionPreset} onPreset={setCompressionPreset} disabled={phase==='processing'}/>:<ToolControls file={files[0]} tool={tool} pageCount={pageCount} selected={selected} setSelected={setSelected} order={order} setOrder={setOrder} range={range} setRange={setRange} splitMode={splitMode} setSplitMode={setSplitMode} interval={interval} setInterval={setInterval} angle={angle} setAngle={setAngle} options={options} setOptions={setOptions}/>}<div className="process-bar"><span><LockKeyhole size={16}/> Runs locally in this tab</span><button className="primary-button" disabled={phase==='processing'||(tool.kind==='merge'&&files.length<2)} onClick={process}>{phase==='processing'&&tool.kind==='compress'&&compressionProgress?compressionStatus(compressionProgress):phase==='processing'?`Processing… ${progress}%`:tool.kind==='compress'?'Compress PDF':tool.kind==='merge'?'Merge PDFs':`${isAnalyzer?'Analyze':'Process'} ${files.length>1?`${files.length} files`:''}`}</button></div>{phase==='processing'&&tool.kind==='compress'&&compressionProgress&&<p className="compression-progress" role="status" aria-live="polite">{compressionStatus(compressionProgress)}</p>}</div></>}
      {phase==='done'&&(tool.kind==='compress'&&compressionResult?<CompressionResultPanel value={compressionResult} onDownload={()=>result&&downloadBlob(result,resultName)} onReset={reset} onTryStrong={()=>{setCompressionPreset('strong');setPhase('configure')}}/>:<div className="result-panel"><span className="success-icon"><Check size={30}/></span><span className="kicker">Complete</span><h2>{isAnalyzer?'Your report is ready':'Your file is ready'}</h2><p>Processing finished locally. Nothing was sent to PDFHope.</p>{report&&<ReportView report={report}/>} {result&&<button className="primary-button download-button" onClick={()=>downloadBlob(result,resultName)}><Download size={19}/> Download {isAnalyzer?'report':'file'}</button>}<button className="secondary-button" onClick={reset}><RotateCcw size={17}/> Start over</button></div>)}
    </section>
    <ToolSeoContent slug={tool.slug}/>
  </main>
}

function FileQueue({files,setFiles,canReorder,onAddFiles}:{files:File[];setFiles:(files:File[])=>void;canReorder:boolean;onAddFiles?: (files:File[])=>void}){const move=(from:number,to:number)=>{if(from===to||to<0||to>=files.length)return;const next=[...files],item=next.splice(from,1)[0];next.splice(to,0,item);setFiles(next)};return <div className="file-queue" onDragOver={(event)=>{if(onAddFiles&&event.dataTransfer.types.includes('Files'))event.preventDefault()}} onDrop={(event)=>{if(onAddFiles&&event.dataTransfer.files.length){event.preventDefault();onAddFiles(Array.from(event.dataTransfer.files))}}}>{files.map((file,index)=><div className="file-card" key={`${file.name}-${file.lastModified}-${index}`} draggable={canReorder} onDragStart={(event)=>event.dataTransfer.setData('text/plain',String(index))} onDragOver={(event)=>event.preventDefault()} onDrop={(event)=>{if(event.dataTransfer.files.length)return;move(Number(event.dataTransfer.getData('text/plain')),index)}}><span className="pdf-badge">PDF</span><span><strong>{file.name}</strong><small>{formatBytes(file.size)}{canReorder?' · drag to reorder':''}</small></span>{canReorder&&<span className="file-order-controls"><button disabled={index===0} onClick={()=>move(index,index-1)} aria-label={`Move ${file.name} up`}><ChevronUp size={16}/></button><button disabled={index===files.length-1} onClick={()=>move(index,index+1)} aria-label={`Move ${file.name} down`}><ChevronDown size={16}/></button></span>}<button onClick={()=>setFiles(files.filter((_,item)=>item!==index))} aria-label={`Remove ${file.name}`}><Trash2 size={17}/></button></div>)}</div>}

function compressionStatus(progress: CompressionProgress) {
  if (progress.stage === 'optimizing') return 'Optimizing document structure…'
  if (progress.stage === 'validating') return 'Validating PDF output…'
  if (progress.stage === 'finalizing') return 'Finalizing PDF…'
  return `${progress.stage === 'analyzing' ? 'Analyzing' : 'Compressing'} page ${progress.page} of ${progress.total}…`
}

function CompressionControls({file,pageCount,preset,onPreset,disabled}:{file:File;pageCount:number;preset:CompressionPreset;onPreset:(value:CompressionPreset)=>void;disabled:boolean}) {
  const choices: {id:CompressionPreset;description:string}[] = [
    {id:'recommended',description:'Best balance. Optimizes document structure while preserving searchable text; recompresses likely scans when safe.'},
    {id:'strong',description:'Smaller visual copy. Uses stronger image compression and may flatten document features.'},
    {id:'maximum',description:'Smallest target. Prioritizes file size over text searchability and fine image detail.'},
  ]
  return <div className="compression-settings"><div className="compression-file-info"><span>Original size <strong>{formatBytes(file.size)}</strong></span><span>Pages <strong>{pageCount}</strong></span></div>{(file.size>50*1024*1024||pageCount>100)&&<p className="compression-signature-note">Large PDFs can use substantial browser memory. If processing fails, close other tabs or try smaller batches.</p>}<fieldset disabled={disabled}><legend>Compression preset</legend><div className="compression-presets">{choices.map(({id,description})=><label key={id} className={preset===id?'selected':''}><input type="radio" name="compression-preset" value={id} checked={preset===id} onChange={()=>onPreset(id)}/><span><strong>{id[0].toUpperCase()+id.slice(1)}</strong><small>{description}</small></span></label>)}</div></fieldset>{preset!=='recommended'&&<p className="compression-warning" role="note">{preset==='strong'?'Strong compression can flatten selectable text, links, form fields and other interactive PDF features.':'Maximum compression can make fine details softer. Text may no longer be selectable or searchable; links and forms can become non-interactive.'} Flattening can also affect annotations, bookmarks and accessibility structure. Creating a compressed copy can invalidate existing digital signatures.</p>}{preset==='recommended'&&<p className="compression-signature-note">Creating a compressed copy can invalidate existing digital signatures. Keep the original.</p>}</div>
}

function CompressionResultPanel({value,onDownload,onReset,onTryStrong}:{value:CompressionResult;onDownload:()=>void;onReset:()=>void;onTryStrong:()=>void}) {
  const explanation = value.noGain
    ? value.preset === 'recommended'
      ? value.structuralStatus === 'complete'
        ? 'No smaller safe copy was found after structural optimization and applicable scanned-page recompression. This PDF may already be highly optimized.'
        : 'No smaller safe copy was found. Structural optimization could not complete in this browser; try again or use Strong if flattening is acceptable.'
      : 'This PDF may already be compact. No smaller copy is available with this preset; keep the original.'
    : value.optimizationMethods.includes('structural')
      ? 'Document structure optimized without page rasterization.'
      : value.optimizationMethods.includes('scanned-page recompression')
        ? `${value.rasterizedPages.length} likely scanned pages recompressed; ${value.hadSearchableText?'searchable pages preserved':'no searchable text was present in the source'}.`
        : 'Pages compressed as a visual copy. Searchable text and interactive features may be flattened.'
  return <div className="result-panel compression-result">
    <span className="success-icon">{value.noGain?<AlertCircle size={30}/>:<Check size={30}/>}</span>
    <span className="kicker">{value.noGain?'Measured result':'Complete'}</span>
    <h2>{value.noGain?'No smaller copy was produced.':'Your smaller PDF is ready'}</h2>
    <p>{explanation}</p>
    <div className="compression-metrics">
      <div><span>Original</span><strong>{formatBytes(value.originalBytes)}</strong></div>
      <div><span>{value.noGain?(value.structuralBytes!==null||value.scanCandidateBytes!==null?'Attempted output':'Original retained'):'Compressed'}</span><strong>{formatBytes(value.outputBytes)}</strong></div>
      <div><span>Saved</span><strong>{formatBytes(value.reductionBytes)} · {value.reductionPercent.toFixed(1)}%</strong></div>
    </div>
    {!value.noGain&&value.reductionPercent<1&&<p className="compression-result-detail">Only a very small reduction was possible.</p>}
    <p className="compression-result-detail">{value.noGain?'Attempted ':''}{value.preset[0].toUpperCase()+value.preset.slice(1)} · {value.originalPageCount} pages · {value.rasterizedPages.length} rasterized · {value.preservedPages.length} preserved</p>
    <p className="compression-result-detail">Searchable text: {value.hadSearchableText===false?'Not present in source':value.textPreservation==='flattened'?'Flattened':value.textPreservation==='partially-preserved'?'Partially preserved':'Preserved'}</p>
    {!value.noGain&&<button className="primary-button download-button" onClick={onDownload}><Download size={19}/> Download compressed PDF</button>}
    {value.noGain&&value.preset==='recommended'&&<button className="primary-button download-button" onClick={onTryStrong}>Try Strong compression</button>}
    <button className="secondary-button" onClick={onReset}><RotateCcw size={17}/> Start over</button>
  </div>
}

type Options={pageSize:string;margin:number;fit:string;format:string;quality:number;scale:number;start:number;size:number;position:string;prefix:string;text:string;opacity:number;watermarkAngle:number;nup:number;landscape:boolean;columns:number}
function ToolControls({file,tool,pageCount,selected,setSelected,order,setOrder,range,setRange,splitMode,setSplitMode,interval,setInterval,angle,setAngle,options,setOptions}:{file:File;tool:NonNullable<ReturnType<typeof getTool>>;pageCount:number;selected:number[];setSelected:(value:number[])=>void;order:number[];setOrder:(value:number[])=>void;range:string;setRange:(value:string)=>void;splitMode:'every'|'ranges'|'interval';setSplitMode:(value:'every'|'ranges'|'interval')=>void;interval:number;setInterval:(value:number)=>void;angle:number;setAngle:(value:number)=>void;options:Options;setOptions:(value:Options)=>void}){
  const update=(key:keyof Options,value:Options[keyof Options])=>setOptions({...options,[key]:value})
  if(tool.kind==='merge'||tool.kind==='interleave')return <p className="setting-note">The files will be combined in the order shown above. Drag cards to change the order.</p>
  if(tool.kind==='images-to-pdf')return <div className="control-grid"><Select label="Page size" value={options.pageSize} onChange={(value)=>update('pageSize',value)} choices={[['a4','A4'],['letter','Letter'],['auto','Match image']]}/><Select label="Image fit" value={options.fit} onChange={(value)=>update('fit',value)} choices={[['fit','Fit — show all'],['fill','Fill — may crop']]}/><NumberField label="Margin (pt)" value={options.margin} min={0} max={72} onChange={(value)=>update('margin',value)}/></div>
  if(tool.kind==='split')return <div className="control-stack"><Select label="Split mode" value={splitMode} onChange={(value)=>setSplitMode(value as typeof splitMode)} choices={[['every','Every page'],['ranges','Custom groups'],['interval','Every N pages']]}/>{splitMode==='ranges'&&<TextField label="Groups separated by semicolons" value={range} placeholder="1-3; 4-6; 8,10" onChange={setRange}/>} {splitMode==='interval'&&<NumberField label="Pages per file" value={interval} min={1} max={pageCount} onChange={setInterval}/>}</div>
  if(tool.kind==='pdf-to-image')return <div className="control-grid"><TextField label="Pages (blank means all)" value={range} placeholder="1, 3, 5-8" onChange={setRange}/><Select label="Resolution" value={String(options.scale)} onChange={(value)=>update('scale',Number(value))} choices={[["1","Standard"],["1.6","High"],["2.2","Very high"]]}/>{options.format==='jpeg'&&<label className="field"><span>JPG quality · {Math.round(Number(options.quality)*100)}%</span><input type="range" min="0.5" max="1" step=".05" value={options.quality} onChange={(event)=>update('quality',Number(event.target.value))}/></label>}</div>
  if(tool.kind==='page-numbers')return <><div className="control-grid"><TextField label="Pages" value={range} placeholder="Blank means all pages" onChange={setRange}/><NumberField label="Starting number" value={options.start} min={0} max={99999} onChange={(value)=>update('start',value)}/><NumberField label="Font size" value={options.size} min={8} max={48} onChange={(value)=>update('size',value)}/><Select label="Position" value={options.position} onChange={(value)=>update('position',value)} choices={[["bottom-left","Bottom left"],["bottom-center","Bottom center"],["bottom-right","Bottom right"],["top-left","Top left"],["top-center","Top center"],["top-right","Top right"]]}/><TextField label="Prefix (optional)" value={options.prefix} placeholder="Page " onChange={(value)=>update('prefix',value)}/></div></>
  if(tool.kind==='watermark')return <div className="control-grid"><TextField label="Watermark text" value={options.text} onChange={(value)=>update('text',value)}/><TextField label="Pages" value={range} placeholder="Blank means all pages" onChange={setRange}/><NumberField label="Angle" value={options.watermarkAngle} min={-90} max={90} onChange={(value)=>update('watermarkAngle',value)}/><label className="field"><span>Opacity · {Math.round(Number(options.opacity)*100)}%</span><input type="range" min=".05" max=".8" step=".05" value={options.opacity} onChange={(event)=>update('opacity',Number(event.target.value))}/></label></div>
  if(tool.kind==='rotate')return <><div className="control-grid"><TextField label="Pages" value={range} placeholder="Blank means all pages" onChange={setRange}/><Select label="Rotation" value={String(angle)} onChange={(value)=>setAngle(Number(value))} choices={[["90","90° clockwise"],["180","180°"],["270","270° clockwise"]]}/></div><PageGrid file={file} pages={pageCount} selected={selected} onSelected={setSelected}/></>
  if(tool.kind==='reorder')return <PageGrid file={file} pages={pageCount} selected={[]} order={order} onOrder={setOrder}/>
  if(tool.kind==='extract'||tool.kind==='delete')return <><TextField label={tool.kind==='delete'?'Pages to remove':'Pages to extract'} value={range} placeholder="1, 3, 5-8" onChange={setRange}/><PageGrid file={file} pages={pageCount} selected={selected} onSelected={setSelected}/></>
  if(tool.kind==='n-up')return <div className="control-grid"><Select label="Pages per sheet" value={String(options.nup)} onChange={(value)=>update('nup',Number(value))} choices={[["2","2 pages"],["4","4 pages"]]}/><Select label="Sheet orientation" value={options.landscape?'landscape':'portrait'} onChange={(value)=>update('landscape',value==='landscape')} choices={[["portrait","Portrait A4"],["landscape","Landscape A4"]]}/></div>
  if(tool.kind==='contact-sheet')return <Select label="Columns" value={String(options.columns)} onChange={(value)=>update('columns',Number(value))} choices={[["2","2 columns"],["3","3 columns"],["4","4 columns"]]}/>
  if(['health','blank','page-size','orientation','duplicate','metadata','deinterleave'].includes(tool.kind))return <p className="setting-note">Ready to process {pageCount.toLocaleString()} page{pageCount===1?'':'s'}. The analysis runs locally and may take longer for large documents.</p>
  return null
}
function TextField({label,value,onChange,placeholder=''}:{label:string;value:string;onChange:(value:string)=>void;placeholder?:string}){return <label className="field"><span>{label}</span><input value={value} placeholder={placeholder} onChange={(event)=>onChange(event.target.value)}/></label>}
function NumberField({label,value,onChange,min,max}:{label:string;value:number;onChange:(value:number)=>void;min:number;max:number}){return <label className="field"><span>{label}</span><input type="number" value={value} min={min} max={max} onChange={(event)=>onChange(Number(event.target.value))}/></label>}
function Select({label,value,onChange,choices}:{label:string;value:string;onChange:(value:string)=>void;choices:string[][]}){return <label className="field"><span>{label}</span><select value={value} onChange={(event)=>onChange(event.target.value)}>{choices.map(([key,name])=><option value={key} key={key}>{name}</option>)}</select></label>}
function ReportView({report}:{report:Record<string,unknown>}){return <div className="report-view">{Object.entries(report).slice(0,9).map(([key,value])=><div key={key}><span>{key.replace(/([A-Z])/g,' $1')}</span><strong>{typeof value==='object'?Array.isArray(value)?value.length?JSON.stringify(value):'None':value?`${Object.keys(value as object).length} fields`:'None':String(value)}</strong></div>)}</div>}
function friendlyError(error:Error){if(/encrypted|password/i.test(error.message))return 'This PDF is password-protected. Remove the password with permission before using this tool.';if(/header|catalog|parse|invalid/i.test(error.message))return 'This file appears to be corrupted or is not a valid PDF.';if(/memory|allocation|out of bounds/i.test(error.message))return 'This PDF exceeded available browser memory. Close other tabs, try Recommended, or use a smaller file or a device with more memory.';return error.message||'Processing failed. Try a smaller file or reload the page.'}
