import { Search } from 'lucide-react'
import { useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { categories, tools } from '../data/tools'
import { ToolCard } from '../components/ToolCard'
import { useSeo } from '../hooks/useSeo'
import { categoryHubs } from '../data/categoryHubs'

const categoryCopy=[['Convert','Move between PDF, Word, Excel, PowerPoint, JPG, PNG, and WebP formats with format-specific controls.'],['Organize','Merge, split, extract, delete, reorder, or rotate document pages.'],['Optimize','Compress scan-heavy PDFs and inspect likely file-size contributors.'],['Edit','Add headers, footers, page numbers, watermarks, annotations, images, or supported text changes.'],['Inspect','Read, OCR and analyze PDF structure, page content and document health.'],['Secure','Add password protection, remove it when you know the password, add visible signatures, and clean standard document metadata.'],['Advanced','Handle duplex scans, duplicate checks, handouts, and contact sheets.']]
export function ToolsPage(){useSeo('All PDF tools','Browse local browser-based tools for organizing, converting, editing, inspecting, and preparing PDFs.','/tools');const[params,setParams]=useSearchParams(),[query,setQuery]=useState(''),active=params.get('category')||'All';const visible=tools.filter((tool)=>(active==='All'||tool.category===active)&&`${tool.name} ${tool.short}`.toLowerCase().includes(query.toLowerCase()));return <main className="listing-page"><div className="listing-head"><span className="kicker">PDFHope toolkit</span><h1>Find your PDF tool</h1><p>Choose a focused PDF workflow and understand what it changes. Most tools process locally; Office conversion pages identify their secure server step.</p><label className="search-box"><Search/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search by task" aria-label="Search all PDF tools"/><span>{visible.length} results</span></label></div><section className="category-directory"><h2>Browse PDF tools by task</h2><div>{categoryHubs.map((hub)=><Link key={hub.path} to={hub.path}><strong>{hub.label}</strong><span>{hub.description}</span></Link>)}</div></section><div className="filter-row">{['All',...categories].map((category)=><button className={active===category?'active':''} key={category} onClick={()=>setParams(category==='All'?{}:{category})}>{category}</button>)}</div><div className="listing-grid">{visible.map((tool)=><ToolCard key={tool.slug} tool={tool} catalog/>)}</div>{!visible.length&&<div className="empty-state"><h2>No matching tool</h2><p>Try a broader phrase or another category.</p></div>}<section className="tools-guide"><span className="kicker">Choose the right workflow</span><h2>What do you need to do with your PDF?</h2><div>{categoryCopy.map(([name,description])=><article key={name}><h3>{name}</h3><p>{description}</p></article>)}</div><p>Start with <Link to="/pdf-reader">PDF Reader</Link> to inspect a file, use <Link to="/edit-pdf">PDF Editor</Link> for supported changes, or run <Link to="/pdf-health-check">PDF Health Check</Link> when a document needs investigation.</p></section></main>}
